---
- name: Creates a directory 
  file:
    path: ~/web
    state: directory

#- name: Extract 
 # unarchive:
  #  src: /home/ubuntu/web/artifact.tar.gz
   # dest: /home/ubuntu/web
    #remote_src: yes

#- name: "install dependencies."
 # become: yes
  #apt:
   # name: ["nodejs", "npm" , "unzip", "tar"]
    #state: latest
    #update_cache: yes

#- name: Extract the artifact
 # shell: | 
  #  cd /home/ubuntu
   # gunzip artifact.tar.gz
    #tar -xvf artifact.tar

- name: Unarchive files 
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: ~/web

- name: Install npm 
  shell: |
    cd ~/web
    npm install

- name: "Run node using pm2"
  #ignore_errors: True
  #async: 100
  #poll: 50
  shell: |
    cd ~/web/dist
    pm2 stop default
    pm2 start npm -- start
    #pm2 start main.js


- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu

#node app.js 
#pm2 start app.js 
#pm2 logs 


